- name: Create /opt/fmd directory for Joplin
  ansible.builtin.file:
    path: /opt/fmd
    state: directory
    mode: "0775"
  become: true


- name: Set FMD user variables
  ansible.builtin.set_fact:
    fmd_user_uid: "1000"
    fmd_user_gid: "1000"

- name: Create /opt/fmd/data directory for FMD SQLite Database
  ansible.builtin.file:
    path: /opt/fmd/data
    state: directory
    mode: "0755"
    owner: "1000"
    group: "1000"
  become: true

- name: Set up FMD secrets
  ansible.builtin.copy:
    dest: /opt/fmd/secrets.env
    mode: "0600"
    content: |
      FMD_REGISTRATIONTOKEN={{ fmd_registration_token }}
  become: true

- name: Create FMD Docker Compose file
  ansible.builtin.template:
    src: files/docker-compose.yaml.j2
    dest: /opt/fmd/docker-compose.yaml
    mode: "0664"
    owner: "root"
    group: "root"
  become: true
  notify: Restart FMD
