- name: Install utility packages
  ansible.builtin.apt:
    name:
      - git
      - htop
      - iftop
      - rsync
      - screenfetch
      - vim
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
