- name: Create /opt/watchtower directory for Watchtower
  ansible.builtin.file:
    path: /opt/watchtower
    state: directory
    mode: "0775"
  become: true

- name: Create Watchtower Docker Compose file
  ansible.builtin.template:
    src: files/docker-compose.yaml.j2
    dest: /opt/watchtower/docker-compose.yaml
    mode: "0664"
    validate: docker compose -f %s config
  become: true
  notify: Restart Watchtower
